apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trakshya-data
  namespace: trakshya-waf
  labels:
    app.kubernetes.io/name: trakshya-waf
    app.kubernetes.io/component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
