apiVersion: v1
kind: Service
metadata:
  name: trakshya-proxy
  namespace: trakshya-waf
  labels:
    app.kubernetes.io/name: trakshya-waf
    app.kubernetes.io/component: proxy
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: trakshya-waf
    app.kubernetes.io/component: proxy
